---
title: "Loop and Function"
author: "Enoch Larrey"
date: "9/24/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loop
# Exercise 1

```{r}
student.df = data.frame( name = c("Sue", "Eva", "Henry", "Jan"),
sex = c("f", "f", "m", "m"),
years = c(21,31,29,19))

student.df$male.teen <- ifelse(student.df$years < 20 & student.df$sex == "m", "T", "F")
student.df
```
# Exercise 2

```{r}
randomNormalDist <- rnorm(3)
reps <- 1

repeat {
    print(randomNormalDist)
    reps <- reps + 1

    if(reps > 10) {
       break}}
```

# Exercise 3

```{r}
cars <- mtcars
for(v in cars[,3]){
  if (v >= 160) print(v)
}
```
# Exercise 4

```{r}
a <- c(3,7,NA, 9)
b <- c(2,NA,9,3)
f <- c(5,2,5,6)
d <- c(NA,3,4,NA)
mydf <- data.frame(a=a,b=b,f=f,d=d)

mydf[,5] <- ifelse(is.na(mydf[,1]) & !is.na(mydf[,2]),
               mydf[,2],
               ifelse(is.na(mydf[,2]) & !is.na(mydf[,4]),
               mydf[,4], mydf[,3]))


mydf
```

# Exercise 5

```{r}
exclude = c(3,9,13,19,23,29)

x <- 0

while(x < 35) {
     x = x+1
     if (x %in% exclude) next
     print(x)}
```
# Excercise 6

```{r}
mat <- matrix(data=NA,nrow=5,ncol=5)
mat

for(i in 1:5){
  for(j in 1:5){
    mat[i,j] = abs(i-j)
  }
}
mat
```

# Function
# Exercise 1

```{r}
Id=c(1:10)
Age=c(14,12,15,10,23,21,41,56,78,12)
Sex=c('F','M','M','F','M','F','M','M','F','M')
Code=letters[1:10]
df=data.frame(Id,Age,Sex,Code)
df
```

```{r}
exchangeCode <- function(df,x,y){
  df[x,'Code']=df[y,'Code']
  df[y,'Code']=df[x,'Code']
  return(df)
}
df = exchangeCode(df,1,3)
df = exchangeCode(df,7,2)
df = exchangeCode(df,5,10)
df
```

# Exercise 2

```{r}
A=c(1:10)
B=seq(100,10,-10)
H=seq(-200,-50,along.with=B)
df <- data.frame(A,B,H)
df
```

```{r}
SUM_x_y <- function(df,x,y){
  for (i in 1:nrow(df))
    df[i,4]=sum(x*df[1:i,1])+sum(y*df[1:i,2])
names(df)[4]=paste('SUM',x,y,sep='_')
df
}

SUM_x_y(df,3,6)
```

# Exercise 3

```{r}
v <- c(2,4,1,7,3,2,7,9)

FUNVector1 <- function(v)
{
  v <- sort(v)*2
  return(v)
}
v <- c(2,4,1,7,3,2,7,9)
FUNVector1(v)
```
```{r}
FUNVector2=function(w){
  w <- as.numeric(w[-which(w %in% letters)])
  w
  w <- FUNVector1(w)
  return(w)
}
a <- c('a','v',4,7,'q')
a <- FUNVector2(a)
a
```
```{r}
b <- c(letters[1:23],10:1,letters[24:26],11:22)
b <- FUNVector2(b)
b
```

