---
title: "Matrix and Data frame"
author: "Enoch Larrey"
date: "9/13/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Matrix
# Exercise 1
```{r}
M <- matrix(c(1:10),nrow=5,ncol=2, dimnames=list(c("a","b","c","d","e"),c("A","B")))
M
```
# Exercise 2

```{r}
x <- c(1, 3, 5)
y <- c(2, 4, 8)
z <- c(3, 6, 9)
A <- cbind(x,y,z)
A
rownames(A) <- c("a", "b", "c")
A
```
# Data Frame
# Exercise 1
```{r}
library(tidyverse)

class(VADeaths)

VADeaths_df <- as.data.frame(VADeaths)
class(VADeaths_df)

VADeaths_df$Total <- apply(VADeaths_df, 1, sum)
VADeaths_df

VADeaths_dfColReord <- select(VADeaths_df, c("Total", "Rural Male", "Rural Female", "Urban Male", "Urban Female"))
VADeaths_dfColReord
```

# Exercise 2

```{r}
class(state.x77)
state.x77_df <- as.data.frame(state.x77)
class(state.x77_df)

state.x77_dfIncless4300 <- subset(state.x77_df, state.x77_df$Income < 4300)
dim(state.x77_dfIncless4300)

highestIncome <- max(state.x77_df$Income)
state.x77_dfHighestInc <- subset(state.x77_df, state.x77_df$Income == highestIncome)
state.x77_dfHighestInc
```
b. 20
c. Alaska

# Exercise 3

```{r}
swiss_df <- swiss
swiss_dfSelected <- swiss_df[c(1:3,10:13), c(3,4,6)]
swiss_dfSelected

swiss_dfSelectedEdited <- edit(swiss_dfSelected)
swiss_dfSelectedEdited

Total <- apply(swiss_dfSelected,2,sum)
Total <- t(as.data.frame(Total))
swiss_dfSelectedTotal <- rbind(swiss_dfSelected,Total)
swiss_dfSelectedTotal

swiss_dfSelectedTotal$Proportion <- swiss_dfSelectedTotal[,"Examination"]/swiss_dfSelectedTotal["Total","Examination"]
swiss_dfSelectedTotal
```

# Exercise 4

```{r}
state_df <- data.frame(state.abb, state.area, state.division, state.name, state.region)
rownames(state_df) <- state_df$state.name
head(state_df)

state.x77_state_df <- cbind(state.x77, state_df)
head(state.x77_state_df)

state.x77_state_df <- subset(state.x77_state_df, select = -state.division)
head(state.x77_state_df)

state.x77_state_df <- subset(state.x77_state_df, select = c(-4, -6, -7, -9, -10))
head(state.x77_state_df)


state.x77_state_df$illiteracy.category <- ifelse(state.x77_state_df$Illiteracy >= 0 & state.x77_state_df$Illiteracy < 1, "low", ifelse(state.x77_state_df$Illiteracy >= 1 & state.x77_state_df$Illiteracy < 2, "some", "high"))

state.x77_state_dfWest <- subset(state.x77_state_df, state.region == "West" & illiteracy.category == "low")
rownames(state.x77_state_dfWest[which.max(state.x77_state_dfWest$Income),])
```

